### ISSUE TITLE
Enable TravisCI for interchange project (requires GitHub Admin user)

### ISSUE THREAD

**Issue by jdigory** [interchange/interchange#100]
@jonjensen @racke @machack666 @SysPete Would one of you GitHub project owners kindly authorize the "interchange" project in Travis CI?

You may need to link your GH account to Travis, then head to: https://travis-ci.org/profile/interchange - and click to enable the interchange/interchange repository.

I will shortly be pushing in a .travis.yml file. Thanks!

**Comment by jonjensen** [comment]
I went to go authorize it, but it says it's already been authorized. Here:

https://github.com/interchange/interchange/settings/hooks/4460047

it says user racke got a token, etc. etc.

So it looks like either Stefan just authorized you but didn't mention it here, or he already had a Travis CI integration set up once upon a time.

**Comment by jdigory** [comment]
Hmpf. The switch still isn't flicked on: https://travis-ci.org/profile/interchange

@racke ?

**Comment by SysPete** [comment]
On 05/07/16 18:11, Josh Lavin wrote:
>
> Hmpf. The switch still isn't flicked on:
> https://travis-ci.org/profile/interchange
>
> @racke <https://github.com/racke> ?
>

On now.

R.
PeteM

**Comment by jdigory** [comment]
Thanks, @SysPete !
