### ISSUE TITLE
demo1 site is broken 

### ISSUE THREAD

**Issue by jdigory** [interchange/interchange#106]
http://demo.icdevgroup.org/i/demo1 

* cgi script not found
* I copied back to /var/www/demo/cgi-bin/ from /tmp/, but IC isn't running
* http://demo.icdevgroup.org/i/demo4 seems to be present, but no demo:demo access to Admin

Unsure what happened, why this broke.

**Comment by jdigory** [comment]
I just ran "testbuild.pl" as demo1 user manually, and it seems to have started everything fine: http://demo.icdevgroup.org/i/demo1

Not sure why this is failing daily.

**Comment by racke** [comment]
Cron jobs have a different environment than user's shell. This could be the explanation why it works with the later, but still unclear why it broke a few weeks ago.

**Comment by jdigory** [comment]
fixed somewhere along the line
