### ISSUE TITLE
RT Ticket #337: DBI does not quote column names -> reserved words will break query

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#12]
Created: Tue Jan 05 09:09:12 2010
Requestors: Gert van der Spoel

---

If a column name turns out to be (or become) a reserved word then queries in Interchange will break (ie set_slice etc) .. This is because column names are not quoted.

(pj: the DBI method quote_identifier() is specifically for that purpose.)

Example: 
Mysql 4 -> 'condition' would be a column name without a problem
Mysql 5 -> 'condition' is a reserved word and needs to be quoted

Boom ...

**Comment by jdigory** [comment]
Fixed by config option added in d904b219
