### ISSUE TITLE
can't create new customer account

### ISSUE THREAD

**Issue by dzhang228** [interchange/interchange#124]
version 5.12

can't create new customer account.

I've been using interchange for years. v 5.12 is a new installation in a new server. The  cart is copied from interchange version 5.6 

Can't find upgrade info to make it work.

**Comment by machack666** [comment]
Hi, do you have any database errors that might say what is happening? What Perl, OS and database version are you using?

**Comment by dzhang228** [comment]
Hi, machack666, Thanks

No database error recorded in error log, both in the catalog or interchange directories
the perl 
~]$  perl -v
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

~]$  mysql -V
mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper

**Comment by dzhang228** [comment]
It turned out to be the mysql version problem, as well as the way a new user account is created.
the new user name and password are not inserted at the same time. In the new mysql server, the non null password field has to have a default value if no value is provided for a new record. So, the new user account can't be created.

Another problem is about the mod_time. There were many  '0000-00-00 00:00:00' when importing data long ago. This prevents the changing of password field to have a null 

My fix:
1, for mod_time:
    UPDATE `userdb` SET `mod_time`=NULL WHERE CAST(mod_time AS CHAR(20)) = '0000-00-00 00:00:00' 
2. Set the default NULL password field.
 
change the password default to NULL

**Comment by jonjensen** [comment]
@dzhang228 Thanks for following up to report what you found.

I just checked the [current MySQL database schema for userdb.password](https://github.com/interchange/interchange/blob/212f8d8ac94f7b6a354c1059ff3d8342d51e2eb6/dist/strap/dbconf/mysql/userdb.mysql#L5) and see it allows NULL, so it sounds like your situation wouldn't arise in a brand new installation. So I'm closing this.
