### ISSUE TITLE
RT Ticket #331: Embedded Perl Encode::Alias problem

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#14]
Created: Wed Nov 18 20:53:32 2009
Requestors: Stefan Hornburg

---

admin/gentable MVSQL query failed for : 'require' trapped by operation mask at /usr/lib/perl/5.10/Encode.pm line 5.
> Compilation failed in require at /usr/lib/perl/5.10/Encode/Alias.pm line 22.
> 
> query was: select code from mv_metadata where type = 'table'

This on Debian squeeze with Perl 5.10.1 (threaded), catalog settings:

Variable MV_UTF8 1
Variable MV_HTTP_CHARSET utf-8

Regards
Racke

**Comment by jdigory** [comment]
Seems to be fixed as of today.
