### ISSUE TITLE
RT Ticket #324: Configuration directive for supported content types

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#15]
Created: Fri Oct 23 13:15:46 2009
Requestors: Stefan Hornburg

---

Hello,

currently this is hardcoded in Server.pm, line 338:

```
if ($CGI::content_type =~ m{^(?:multipart/form-data|application/x-www-form-urlencoded|application/xml|application/json)\b}i) {
parse_post(\$CGI::query_string)
if $Global::TolerateGet;
parse_post($h->{entity});
}
else {
## invalid content type for POST
## XXX we may want to be a little more forgiving here

my $msg = ::get_locale_message(415, "Unsupported Content-Type for POST method");
my $content_type = $msg =~ /<html/i ? 'text/html' : 'text/plain';
my $len = length($msg);
$Vend::StatusLine = <<EOF;
Status: 415 Unsupported Media Type
Content-Type: $content_type
Content-Length: $len
EOF
respond('', \$msg);
die($msg);
}
}
```

Carl Bailey suggested on the mailing list to create a configuration directive for supported content types:

http://www.icdevgroup.org/pipermail/interchange-users/2009-October/051266.html

Regards
Racke

**Comment by jonjensen** [comment]
JSON works fine now, so the original problem report is solved. Future configurability to be discussed by someone needing it and with a plan to do the work.
