### ISSUE TITLE
RT Ticket #315: Error with UTF-8 characters in files included from catalog.cfg

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#17]
Created: Fri Sep 11 10:50:19 2009
Requestors: Stefan Hornburg

---

Configuring catalog ulisses...UserTag 'publication_date' subroutine failed safe check: Unrecognized character \xC3 in column 137 at (eval 6056) line 7, <CONFIG> line 51.

The file contains strings with UTF-8 characters.

The configuration parse in Config.pm apparently doesn't open the file
in the correct mode.

The UTF8 variables are set in the catalog only:

```
# Encoding

Variable MV_UTF8 1
Variable MV_HTTP_CHARSET utf-8
# Custom functions

include code/_._
```

Regards
Racke

**Comment by jonjensen** [comment]
I believe this was fixed in issue #118.
