### ISSUE TITLE
RT Ticket #313: Stock message mismatch in standard catalog

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#19]
Created: Wed Sep 09 12:45:02 2009
Requestors: Stefan Hornburg

---

inventory.txt: stock_message
inventory.lite/.mysql: stock_msg
inventory.pgsql: -
flypage.html: stock_message

Please fix this mismatch. 

Regards
Racke

**Comment by jonjensen** [comment]
I just fixed this triviality in commit bb50ffd67e8fcd68777.
