### ISSUE TITLE
RT Ticket #297: removing MV_DEFAULT_SEARCH_FILE / MV_DEFAULT_SEARCH_TABLE ?

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#22]
Created: Sun Jul 12 08:49:17 2009
Requestors: Gert van der Spoel

---

Adding additional tables to search on using the catalog config directive ProductFiles does initially appear to not work:

ProductFiles products products2

However this is caused by the following lines found in 
interchangd/catalog_before.cgi:
## Deprecated, could be removed in IC 5.2 (line added in 2003)

Variable MV_DEFAULT_SEARCH_FILE products 
Variable MV_DEFAULT_SEARCH_TABLE products
- In what way are these Variables deprecated?
- Should code making use of these Variables be removed from:
  Vend/Config.pm
  Vend/DbSearch.pm
  Vend/Glimpse.pm
  Vend/Scan.pm
  Vend/TextSearch.pm

Peter suggested on IRC that we could look at removing these variables from the tree and add to the upgrade document to suggest the alternative settings (such as adding to the directive ProductFiles ) ...

**Comment by jonjensen** [comment]
I removed the comment in commit 5f0ced0e2c2cb because the variable is ensconced in core and not going away.
