### ISSUE TITLE
RT Ticket #286: Incorrect detection of MV_GETPPID_BROKEN var. setting

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#23]
Created: Fri Jun 26 10:30:59 2009
Owner: Stefan Hornburg
Requestors: Davor Ocelic

---

When IC is installed on a clean SuSE install which has Perl
5.10, value of MV_GETPPID_BROKEN is set to 1 which is not
correct, and the server fails to start.

**Comment by jdigory** [comment]
counting this as fixed since it was fixed in master, plus the perl used is ancient.
