### ISSUE TITLE
RT Ticket #285: Make makecat query for DBA username and password

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#24]
Created: Fri Jun 26 09:51:40 2009
Requestors: Stefan Hornburg
Cc: Sebastian Kliess

---

Every sane DBMS doesn't allow to create databases without a password, so
makecat really needs to provide a way to pass this credentials safely.

Regards
Racke

**Comment by jdigory** [comment]
this is what "extra options for creation" is for
