### ISSUE TITLE
RT Ticket #282: Create shipping package tracking API in Vend::Ship namespace

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#25]
Created: Fri Jun 19 08:35:16 2009
Owner: Mark Lipscombe

---

One of our old user tags that does package tracking.

We should considering splitting this up and convert it to something more
generic in Vend::Ship::Track, and create a simple usertag that takes the
tracking number, and optionally the carrier (otherwise do
autodetection). We should also add XML::XPath and its dependencies to
one of the standard Bundles.

--

https://gist.github.com/phinjensen/5163734
https://gist.github.com/phinjensen/5163752

**Comment by jdigory** [comment]
this is so old that it probably doesn't work today
