### ISSUE TITLE
RT Ticket #269: Problems with non-UTF-8 character in [L]...[/L] tags

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#26]
Created: Wed May 13 09:44:20 2009
Owner: David Christensen
Requestors: Stefan Hornburg

---

Log file:

127.0.1.1 zbt8EdKB:127.0.1.1 - [13/May/2009:10:18:34 +0200] ulisses
/cgi-bin/ic/ulisses/reviews/create Runtime error: Malformed UTF-8
character (fatal) at /usr/lib/interchange/Vend/Util.pm line 1052.
> 

Excerpt from Util.pm:

sub parse_locale {
my ($input) = @_;

return if $::Pragma->{no_locale_parse};

# avoid copying big strings
my $r = ref($input) ? $input : \$input;

The last line is line 1052.

Regards
Racke

**Comment by jdigory** [comment]
closing, needs more info so we can attempt to reproduce. Also sounds like it is probably fixed in later releases.
