### ISSUE TITLE
RT Ticket #268: File.pm regression: binary uploads getting corrupted

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#27]
Created: Mon May 11 07:23:06 2009
Owner: Stefan Hornburg
Requestors: Peter Ajamian

---

If MV_UTF8 is turned on then uploads done via the image upload widget in
the UI are being corrupted. It appears that writefile() is attempting
to encode the binary image file as UTF8 before writing it out. This is
a regression as of this patch:
http://www.icdevgroup.org/pipermail/interchange-cvs/2009-April/007738.html

Note that reverting File.pm back to revison 2.30 causes the problem to
go away.

**Comment by jonjensen** [comment]
I see handling for encoding, defaulting to "raw" when it's not a `text/*` content-type, so I think this has been fixed for a long time.
