### ISSUE TITLE
RT Ticket #256: nginx support and documentation

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#28]
Created: Fri Mar 06 16:03:41 2009
Requestors: Stefan Hornburg 

---

Please configure nginx to work with Interchange and add this to the
documentation.

Regards
Racke

**Comment by jdigory** [comment]
We don't even show how to use Apache :-)

**Comment by jonjensen** [comment]
Yep, docs requests could be infinite. Closing.
