### ISSUE TITLE
RT Ticket #227: IC does not handle correctly postgres field-names with mixed case

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#34]
Created: Wed Oct 01 08:26:18 2008
Requestors: Rene Hertell

---

If using field-names with mixed case, ic does not "see" them. 

This can easily be reproduced by adding eg. description_fi_FI to the
products-db, and trying to display it on the flypage with [item-field
description_fi_FI].

Lowercasing the tablename in the postgres-table makes the field-content
to show up.

here some info about this:
http://search.cpan.org/~mergl/DBD-Pg-1.01/dbd-pg.pod#Table_and_Column_Names

This makes problems if you use mv_locale for figuring out
field/table-names with mixed case.

**Comment by jonjensen** [comment]
This was fixed long ago with the addition of the database attribute `QUOTE_IDENTIFIERS`.
