### ISSUE TITLE
RT Ticket #223: inventory.pgsql enhancement/bugfix?

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#35]
Created: Tue Sep 23 12:05:26 2008
Requestors: Rene Hertell

---

The default colmuntype is missing in this file.
Database inventory DEFAULT_TYPE varchar(128)

Index: dist/standard/dbconf/pgsql/inventory.pgsql
===================================================================
RCS file: /var/cvs/interchange/dist/standard/dbconf/pgsql/inventory.pgsql,v
retrieving revision 1.1.1.1
diff -u -p -u -r1.1.1.1 inventory.pgsql
--- dist/standard/dbconf/pgsql/inventory.pgsql 25 Apr 2004 17:07:49 -0000 1.1.1.1
+++ dist/standard/dbconf/pgsql/inventory.pgsql 23 Sep 2008 11:33:13 -0000
@@ -1,4 +1,5 @@
Database inventory inventory.txt __SQLDSN__
+Database inventory DEFAULT_TYPE varchar(128)
Database inventory KEY sku
Database inventory COLUMN_DEF "sku=VARCHAR(64) NOT NULL PRIMARY KEY"
Database inventory COLUMN_DEF "quantity=VARCHAR(12)"

**Comment by jdigory** [comment]
The default_type is char(128), so individual db config files don't require their own.
