### ISSUE TITLE
RT Ticket #220: Authen::Captcha module alternative

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#37]
Created: Wed Sep 17 05:46:50 2008
Requestors: Stefan Hornburg

---

Authen::Captcha was last updated in 2003. It appears doubtful to me that
it will work any good with all the development in this area since then.

Regards
Racke

**Comment by jdigory** [comment]
Authen::Captcha received updates in 2012, so no longer an issue. Also CAPTCHA support from Interchange itself is never going to be as good as an external service like reCAPTCHA.
