### ISSUE TITLE
RT Ticket #217: Extend natural number order check

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#38]
Created: Mon Aug 25 09:01:13 2008
Owner: Stefan Hornburg

---

From Wikipedia (http://en.wikipedia.org/wiki/Natural_number):

In mathematics, a natural number (also called counting number) can mean
either an element of the set {1, 2, 3, ...} (the positive integers) or
an element of the set {0, 1, 2, 3, ...} (the non-negative integers). The
former is generally used in number theory, while the latter is preferred
in mathematical logic, set theory, and computer science. A more formal
definition will follow.

Aside from that it would be useful to optional allow 0 to be included in
the set of numbers.

Regards
Racke

**Comment by jonjensen** [comment]
This would be easy but there is apparently no demand for this change.
