### ISSUE TITLE
RT Ticket #215: Hide errors from end users

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#39]
Created: Mon Aug 25 08:31:49 2008
Requestors: Jure Kodzoman

---

Warn about but don't display errors in the infobox. Users shouldn't see
the SQL query etc., but rather a general message, while the error should
appear in logs only

**Comment by jdigory** [comment]
a template issue, can be solved by:
`DatabaseDefault LOG_ERROR_SESSION 0`
