### ISSUE TITLE
RT Ticket #206: Wrong catalog root leads to confusing error message

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#42]
Created: Wed Jul 02 21:04:07 2008
Requestors: Stefan Hornburg 

---

If the directory in the "Catalog" directive exists and is writeable by
Interchange, it gives the following confusing error message when a
catalog.cfg doesn't exist there.

Regards
Racke

**Comment by jonjensen** [comment]
Patches welcome, but otherwise closing this.
