### ISSUE TITLE
RT Ticket #202: Error handling for emails sent through Net::SMTP

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#43]
Created: Thu Jun 05 10:39:38 2008
Requestors: Stefan Hornburg 

---

Ton Verhagen reported on interchange-users:

I have the following in catalog.cfg

Variable MV_SMTPHOST localhost.localdomain
SendMailProgram Net::SMTP

The catalog generates many lines in the error.log like:

Unable to send mail using Net::SMTP (mail server localhost.localdomain)
and
Unable to send mail using Net::SMTP

However, it seems that the mail is sent out properly.

I tried a couple of things in order to narrow things down.
1. Action: send a mail using the email tag in the test code field in the
   admin
   Result: mail is sent, no error message in error.log
2. Action: placed a test order
   Result: Customer mail well received, however an error message in error.log
   Error: Unable to send mail using Net::SMTP (mail server
   localhost.localdomain)

Even if sending emails works, the error handling/reporting needs to be
improved.

Regards
Racke

**Comment by jonjensen** [comment]
I haven't seen this elsewhere and wonder if it was due to a local configuration problem. Closing, and someone can re-file when they confirm and fix.
