### ISSUE TITLE
RT Ticket #196: Database conversion osCommerce -> Interchange

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#45]
Created: Thu May 15 18:32:29 2008
Requestors: Gert van der Spoel

---

On the core-list a suggestion was made to look at possibilities to
convert an osCommerce database to the Interchange datamodel. 

Sounds like a good plan, so here's a ticket to remember :)

**Comment by jonjensen** [comment]
This would be nice but nobody ever stepped up to do it. Now it would make more sense to write a migrator from WooCommerce or Magento. We don't need to keep track of unfunded dreams like this one anymore. :smile:
