### ISSUE TITLE
RT Ticket #195: Fix PostgreSQL 8.3 compatibility

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#46]
Created: Tue May 13 23:03:38 2008
Requestors: Jon Jensen 

---

(I just posted this to interchange-users:)

In PostgreSQL 8.3 many implicit casts were removed, some of which
Interchange relied on. By default, the Standard demo and some
Interchange core SQL does not work with PostgreSQL 8.3.

We expect to work around this in a future version of Interchange, but at
the moment the easiest way to get things working is to manually put
back the removed casts, as Peter Eisentraut describes here:

http://people.planetpostgresql.org/peter/index.php?/archives/18-Readding-implicit-casts-in-PostgreSQL-8.3.html

Running his pg83-implicit-casts.sql script fixes the known problems with
the Standard demo.

This issue affects all versions of Interchange, but does not affect
earlier versions of PostgreSQL.

**Comment by jdigory** [comment]
This is mentioned in the UPGRADE guide: https://github.com/interchange/interchange/blob/master/UPGRADE#L92

with supporting file here: https://github.com/interchange/interchange/blob/master/eg/pg83-implicit-casts.sql

Thus, no other action deemed necessary at this time.
