### ISSUE TITLE
RT Ticket #188: Mysql dbconf file updates

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#47]
Created: Wed Apr 23 21:48:39 2008
Requestors: Gert van der Spoel

---

Attached is a tar.gz file with patches for the dbconf files for mysql.
I did this about 2 years ago, but I think the changes are still relevant.

Could someone review the changes? 
I can commit changes, but if someone else (the person who checks the
patches?) commits them that would be fine too.

(Attached is a broken tar.gz file)

**Comment by jdigory** [comment]
can't fix, lost attachment.
