### ISSUE TITLE
RT Ticket #166: Change the use of the date-widget to date_blank widget

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#49]
Created: Tue Mar 11 11:42:47 2008
Requestors: Rene Hertell 

---

It would be better to use the date_blank widget for all places in the
demo. now if someone edits a record what does not need a date, it will
get forced to have the current date..

**Comment by jonjensen** [comment]
The demo nowadays is not the same one as when this was reported, so I'm closing this.
