### ISSUE TITLE
RT Ticket #156: Search result paging with clean URLs

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#50]
Created: Wed Jan 23 11:48:24 2008
Requestors: Stefan Hornburg

---

Hello,

the links for the search result paging currently look like:

scan/MM=4c06d7cf12f118e90e1a936a9df3ece3:1:6:6.html

This is bad for SEO and a facility should be added to produce
clean URLs, at least with a relatively static dataset
(mv_more_permanent doesn't seem to help with that).

Regards
Racke

**Comment by jdigory** [comment]
should be controlled in the templates
