### ISSUE TITLE
RT Ticket #130: --email option allows only one address

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#52]
Created: Thu Nov 08 11:14:33 2007
Requestors: Stefan Hornburg

---

A job triggered with the following command will send email only to
racke@linuxia.de:

interchange --email=racke@linuxia.de,hornburg@cobolt.net
--runjobs=matstock=uploads

Regards
Racke

**Comment by jonjensen** [comment]
A patch to improve this would be welcome, but scripts/interchange.PL documents this as one email only, so it's currently working as advertised. Having said that, in reviewing the code, I don't see any reason multiple addresses wouldn't work. But Stefan, you made the most recent changes to this just a few months prior to your report in commit be1f7b10c701c83cc826c0a7c7834bb23b53f75c, so if you never tracked it down, I don't think anyone better will come along to do it, so I'm closing it.
