### ISSUE TITLE
RT Ticket #127: Odd behaviour in function/stock_alert.html

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#54]
Created: Sun Oct 21 20:18:07 2007
Requestors: Rene Hertell 

---

In the demo-shop is an odd behaviour:

If the user changes the email-preference ("Put me on your email list of
infrequent offers") on the function/stock_alert.html page, the form
gets automagically submitted.

I would rather let the user decide if he wants to submit the form or
not. I would suggest that the "onChange="this.form.submit()" should be
removed from this form so that the user does not submit the form against
his will :-

**Comment by jdigory** [comment]
standard demo no longer supported
