### ISSUE TITLE
RT Ticket #124: AUTO_SEQUENCE with DatabaseAuto

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#55]
Created: Thu Sep 27 20:52:53 2007
Requestors: Jure Kodzoman 

---

It would be nice if you define DatabaseAuto, you wouldn't have to still
write AUTO_SEQUENCE for every table.

That would take all the table stuff out from config, and made editing
and adding tables much easier.

**Comment by jonjensen** [comment]
This would be nice. I don't think Interchange's database abstraction layer is worth adding a lot more features too, though, when there are many great ORMs to use from Perl code.
