### ISSUE TITLE
RT TIcket #117: SOAP server crashing

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#59]
Created: Thu Sep 13 23:15:01 2007
Requestors: Stefan Hornburg 

---

127.0.0.1 vPzJsmAT:127.0.0.1 - [13/September/2007:19:11:16 -0400]
soapopera /soapopera SOAP died in processing: error 'No such process'
from select, n=-1. at /usr/lib/interchange/Vend/Server.pm line 2061.

This is Server.pm 2.81, within the following code:

```
if ($n == -1) {
    last if $!{EINTR} and $Signal_Terminate;
    my $msg = $!;
    $msg = ::errmsg("error '%s' from select, n=%s.", $msg, $n );
    die "$msg";
}
```

**Comment by jonjensen** [comment]
This is ancient and hasn't been reported since, so I'm closing it.
