### ISSUE TITLE
RT Ticket #350: SystemTag/assign.coretag parsing an int

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#6]
Created: Mon Mar 19 15:56:53 2012
Owner: Anonymous

---

interchange/code/SystemTag/assign.coretag tries to detect illegal assignments of non-numbers to numeric database fields. The validation is wrong, resulting in many "Attempted assign of non-numeric" warnings.

A better check would be:
- if($value =~ /^-?\d+.?\d*$/ )
- if($value =~ m/ ^[+-]?[0-9]+$ | ^[+-]?[0-9]*.[0-9]+$ /x ) {

Mind you: \d ~= [0-9]

By the way: this fix broke quite some code in my instance. Handle with care!

**Comment by jonjensen** [comment]
This could surely be done better, but as the original poster wrote, fixing it broke a lot of code. Given that the main problem is noise in the error logs, closing this.
