### ISSUE TITLE
RT Ticket #112: Upgrade splats catalog_before.cfg and catalog_after.cfg

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#61]
Created: Mon Aug 20 22:44:44 2007
Requestors: Kevin Walsh

---

The catalog_before.cfg file should be renamed to catalog_before.cfg.dist
(same with catalog_after.cfg) and only installed if the non-dist file
doesn't exist.

If the non-dist file exists then leave the .dist file in place to allow
the administrator to compare the differences (if any) and install manually.

**Comment by jonjensen** [comment]
Swish-e has been unmaintained since 2010, so closing.

**Comment by jonjensen** [comment]
This was fixed long ago, but broken again due to a simple bug in commit da07bbc37a7d92851c7ffa597313c383653e108e and now is fixed again in commit a69fe8de23048dc33aa0f65099590fdfc02e9e84.
