### ISSUE TITLE
RT Ticket #111: Swish2 module problem with [on-match] and [no-match] blocks

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#62]
Created: Mon Aug 20 19:50:06 2007
Owner: Stefan Hornburg
Requestors: Kevin Walsh

---

The recent Swish2 module changes caused the [on-match] and [no-match]
blocks to reverse their meaning on results pages.

I use Swish2 on the www.interchange.rtfm.info website, but I got around
the problem by simply overwriting Swish2.pm with an old version.

Now that a 5.5.1 release is due, I deemed it inappropriate to provide a
broken Swish2.pm, so I looked into it a little.

I found a line that avoided the problem when commented out, so I just
did that for the time being. Commenting out the call to build_search()
causes most of the new code to not be called, thus avoiding the problem.

I haven't had time to look into what part of the new code is causing the
problem, so I'm raising this bug report instead.

It's bound to turn out to be be something simple.

**Comment by jonjensen** [comment]
Swish-e has been unmaintained since 2010, so closing.
