### ISSUE TITLE
RT Ticket #96: Content editor botches perl code with curly braces

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#66]
Created: Thu Aug 02 07:45:30 2007
Requestors: Stefan Hornburg

---

The following perl chunk in my page:

    [perl table="subjects"]
    my (@out, $set, $subject);
    
    my $set = $Db{subjects}->query({sql => "select subject from subjects
    where sku = '[item-code]' order by subject"});
    
    for (@$set) {
        $subject = $_->[0];
        $url = $Tag->area({href => "subject/$subject"});
        push (@out, qq{<a href="$url">$subject</a>});
    }
    
    if (@out) {
        return '<p>Subjects: ' . join(', ', @out) . '</p>';
    }

    return '';
    [/perl]

turns out in the content editor of the UI as:

    [perl table="subjects"]
    my (@out, $set, $subject);
    
    my $set = $Db{subjects}->query();
    
    for (@$set) {
        $subject = $_->[0];
        $url = $Tag->area();
        push (@out, qq{<a href="$url">$subject</a>});
    }

    if (@out) {
        return '<p>Subjects: ' . join(', ', @out) . '</p>';
    }

    return '';
    [/perl]

Regards
Racke

**Comment by jdigory** [comment]
Content Editor is no longer supported.
