### ISSUE TITLE
RT Ticket #65: Duplicate form-submission preventer

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#67]
Created: Thu Jul 05 21:15:21 2007
Requestors: Davor Ocelic

---

I talked to Stefan about the way to prevent duplicate form submissions.

I think, roughly, the idea was that we need to write code that would
track form submissions.

That code should somehow accept options, so that you can specify that:

- form is not to be submitted again ever during the session, or
- form is not to be submitted again until at least some data is
different, or
- form is not to be submitted again for some time interval

This idea can take some more refinements, of course. So please comment
here to prepare the material for the implementer who takes it.

**Comment by jdigory** [comment]
This is a template-level issue.
