### ISSUE TITLE
RT Ticket #64: HTTP status code from link script

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#68]
Created: Thu Jul 05 20:06:29 2007
Requestors: Stefan Hornburg

---

The link script should be a bit more configurable. Not much to keep it
as quick as possible. But it would be great to assign a HTTP code to the
case where the Interchange server isn't available and use an error
handler to display a customer-friendly message.

**Comment by jonjensen** [comment]
This was done in:

* commit 8a56977f695 returning HTTP status codes 503 or 504 when Interchange isn't available.
* commit 06ecaad090b0b622 returning HTTP status code 504 in one case and messages configurable at compile time.

Post-compile configurability in the environment or some configuration file would be possible, but this is good enough for now IMO.
