### ISSUE TITLE
RT Ticket #349: Vend::Util::round_to_frac_digits() simplification

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#7]
Created: Mon Mar 19 15:47:34 2012
Owner: Anonymous
Requestors: Mark Overmeer

---

round_to_frac_digits() produces ".00" when called with (0, 2). It also parses the integers incorrectly: in normal Perl "1." is a valid number, as is "+3", but "-" is not valid.

Nearly all of the function logic can be replaced with:

printf "%.*f", $digist, $num;

**Comment by jonjensen** [comment]
This is a discussion about how to implement decimals throughout Interchange, which isn't going to change in core at this late date.
