### ISSUE TITLE
RT Ticket #49: Fuzz tests should be written

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#70]
Created: Tue Jul 03 07:00:00 2007
Requestors: Mick Weiss

---

I've found that NULL strings in the products table can cause issues.

I ran into this before where I was getting something like
Vend::NULL::options -- due to NULL values in the database. I have not
been able to reproduce this (I haven't tried very hard though). I
haven't filed a bug since I can't reproduce it.

Fuzz tests (http://en.wikipedia.org/wiki/Fuzz_testing#Database_fuzz)
should help find problems before they start.

**Comment by jdigory** [comment]
Need to be able to reproduce...
