### ISSUE TITLE
RT Ticket #42: Removal of Userdb Record failed

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#71]
Created: Sat Jun 30 14:18:04 2007
Owner: Gert van der Spoel
Requestors: Stefan Hornburg

---

The userdb of one of my catalogs has users heike and Heike. This appears
to be legal with GDBM, but removal of heike from the UI fails silently.

Regards
Racke

**Comment by jonjensen** [comment]
I think we all consider GDBM for userdb pretty much deprecated these days, so closing.
