### ISSUE TITLE
RT Ticket #34: More lists doesn't work with [loop object=`$Scratch->{result}`]

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#74]
Created: Fri Jun 29 21:03:10 2007
Requestors: Gert van der Spoel

---

Code to reproduce the problem:

    [perl]
    # get product list first
    my (%products, $pset);
    
    my $pset = $Db{products}->query({sql => 'select sku,title,isbn,category
    from products',
    hashref => 1});

    for (@$pset) {
        $_->{count} = 0;
        $products{$_->{sku}} = $_;
    }

    # get orders and associate to products
    my $oset;

    $Scratch->{query} = qq{select sku,title,count(sku) as count from
    orderline $cstr group by 
    sku,title order by count desc};

    $oset = $Db{orderline}->query({sql => $Scratch->{query}, hashref => 1});

    for (@$oset) {
        if (exists $products{$_->{sku}}) {
            $products{$_->{sku}}->{count} += $_->{count};
        } else {
            $products{$_->{sku}} = $_;
        }
    }
    
    my @results = sort {$b->{count} <=> $a->{count}} values %products;

    $Scratch->{result}->{mv_results} = \@results;
    #$Scratch->{result}->{mv_field_names} = [qw(sku title isbn category count)];
    return;
    [/perl]

    [loop object=`$Scratch->{result}` prefix=sql list=1 more=1 ml="[value
    count]"]
    [on-match]
    <table>
    <tr><th>Orders</th><th>Title</th><th>ISBN</th><th>Category</th></tr>
    [/on-match]
    [list]
    <tr><td>[sql-param count]</td><td>[sql-param sku] <a href="[area 
    href="admin/reports/order/BySKU" form="sku=[sql-param sku]"]">[sql-param 
    title]</a></td><td>[sql-param isbn]</td><td>[sql-param category]</td></tr>
    [/list]
    [on-match]
    </table>
    [/on-match]
    [more-list][more][/more-list]
    [/loop]

**Comment by jdigory** [comment]
This code is fraught with errors. I tried... Suffice it to say that `[loop object=]` works fine in my experience.
