### ISSUE TITLE
RT Ticket #27: Nested elsifs with named parameters parsed incorrectly

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#76]
Created: Fri Jun 29 11:32:50 2007
Requestors: Gert van der Spoel

---

The following code exposes a problem parsing nested elsifs
with named parameters. The result is "INCORRECT 2" instead
of "CORRECT".

[tmpn name="test"]1[/tmpn]
[if type="scratch" term="test" op="eq" compare="2"]
INCORRECT 1
[elsif type="scratch" term="test" op="eq" compare="1"]
[if type="scratch" term="test" op="eq" compare="2"]
INCORRECT 2
[elsif type="scratch" term="test" op="eq" compare="1"]
CORRECT
[/elsif]
[/if]
[/elsif]
[/if]

**Comment by jonjensen** [comment]
ITL is a minefield and should be avoided for complex logic. Let's use compiled Perl instead.
