### ISSUE TITLE
RT Ticket #21: No CSV import possible in UI

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#77]
Created: Thu Jun 28 23:22:47 2007
Requestors: Anonymous

---

This is taken from: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=388385

I verified this on my own machine.

Test included. Put the csv in /tmp before running the test.

388385-fixedwidth.csv
    sku description titletemplate_page comment thumb image price wholesale prod_group category tax_category nontaxable weight option_type author related featured gift_certdownload dl_type dl_locationinactiveurlsale_priceimage_large 
40934Shiny Red 05 1 pc./Alu. 12.9 5.2Sante Lipsticks Natural Shine

https://gist.github.com/uncleshelby/5238252

**Comment by jonjensen** [comment]
This was marked as a wishlist item in the original Debian bug report. Too many wishes to worry about one like this. Closing.
