### ISSUE TITLE
RT Ticket #346: Can't setup DBI handle of DBI::st=HASH(0xaff6bb0) to DBD::mysql::st_mem: unknown

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#8]
Created: Wed Apr 06 07:34:41 2011
Owner: Gert van der Spoel

---

IC: 5.7.6 (but possibly other versions)
Perl: 5.12.3

When doing something like 
[xxx-exec bar_link]yyyy[/xxx]

The following crash occurs:
Can't setup DBI handle of DBI::st=HASH(0xaff6bb0) to DBD::mysql::st_mem: unknown _mem package at /export/opt/perl-5.12.3/lib/site_perl/5.12.3/i686-linux/DBI.pm line 1285.

This happens in
/path/to/interchange/catalog_before.cfg

line 70:
my $record = tag_data($base, 'n/a', $code, { hash => 1 });

Currently there are 2 possible workarounds:
1) Downgrade to Perl 5.10
2) set AllowGlobal <catalog> for the catalog using this code.

Both workarounds are not perfect. Assumption has been made it has to do with Safe ... Perhaps there is an Untrap possibility to work around this as well.

**Comment by jonjensen** [comment]
This is no longer relevant, as `sub bar_link` is no longer part of Interchange / Strap.
