### ISSUE TITLE
RT Ticket #5: Automatic Creation of Log Rotation Configuration File

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#82]
Created: Thu Jun 28 15:06:15 2007
Requestors: Peter Ajamian

---

There is no standard routine to create logrotate configuration for
individual catalogs, although we can easily find the location of the
existing catalogs by looking into the status.* files in the runtime
directory.

**Comment by jdigory** [comment]
Closing since example logrotate was added, and there isn't more we can do.
