### ISSUE TITLE
RT Ticket #1: Cronjob doesn't remove the files in the catalog tmp directories

### ISSUE THREAD

**Issue by phinjensen** [interchange/interchange#83]
Created: Thu Jun 28 13:23:00 2007
Requestors: Gert van der Spoel

---

The current out of the box provided expiration scripts / cron jobs do
not remove files in the catalog tmp directories. 

This could eventually result in a full disk.

**Comment by jonjensen** [comment]
True. Most of us have used various shell scripts of our own for years, not just for `tmp` but also `timed` and other things. But it's good to have an example. I added one in commit 212e265b5d44da1eb0692829f9aac7ed1901a20a.
