### ISSUE TITLE
Promoting admin passwords without required modules nukes password

### ISSUE THREAD

**Issue by racke** [interchange/interchange#90]
This can be reproduced on the public demo:
- Refresh the demo.
- Login to admin works, but shows these errors:
  `89.182.156.213 IHQx4xUo:89.182.155.99 - [23/January/2016:13:40:21 +0000] demo1 /i/demo1/process Bcrypt passwords unavailable. Are Digest::Bcrypt and Crypt::Random installed?
  89.182.156.213 IHQx4xUo:89.182.155.99 - [23/January/2016:13:40:21 +0000] demo1 /i/demo1/process Bcrypt passwords unavailable. Are Digest::Bcrypt and Crypt::Random installed?`
- Logout from admin
- Next login fails with this error:
  `89.182.156.213 IHQx4xUo:89.182.155.99 - [23/January/2016:13:40:27 +0000] demo1 /i/demo1/process Refusing to use blank password from 'access' database for user 'demo'`

**Comment by racke** [comment]
On top of that Crypt::Random is hard to install and isn't really not the module of choice otherwise (ask @SysPete about using /dev/random...).

**Comment by jdigory** [comment]
Line 138 of UserDB.pm says it's using /dev/urandom. Not sure if that allays your concerns or not, or even if it does what it says...

**Comment by jdigory** [comment]
It should be noted that installing the Bundle::Interchange CPAN module will prevent this, although I agree the behavior is wrong.

Swapping out Crypt::Random for something else is a feature request and can be created as a new issue.

**Comment by racke** [comment]
Interchange isn't easy to install in the first place, and Crypt::Random makes it even harder. We need an alternative, otherwise I'm not going to provide .deb packages.

**Comment by jdigory** [comment]
Opened #96 for the Crypt::Random suggestion. This issue remains open for the bug of nuking passwords.

**Comment by jonjensen** [comment]
@racke Yikes -- this is a bad bug. I confirmed it and pushed a fix in commit c98351729df1.
