### ISSUE TITLE
Cloning product from Admin gives error

### ISSUE THREAD

**Issue by jdigory** [interchange/interchange#92]
Confirmed in IC 5.10

`table products: set_slice error as called by Vend::Data: DBD::mysql::st execute failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '='',='',='',='os28082_b.gif',='24\" Level clone',='os28082.gif',='Measuring Tool' at line 1 at /home/demo1/interchange/lib/Vend/Table/DBI.pm line 1412. query was:update`products`SET =?,=?,=?,=?,=?,=?,=?,=?,=?,=?,=?,=?,=? WHERE`sku`= 'os29001' values were:'','','','os28082_b.gif','24" Level clone','os28082.gif','Measuring Tools',' Certified accuracy, High strength, long life, Built-in rubber grips for usefulness. Easy to clean.','1','','Levels','34.99','17.5'`

**Comment by jdigory** [comment]
cannot duplicate locally, only on demo.icdevgroup.org

**Comment by jonjensen** [comment]
I believe this was fixed in commit 4921b6e1f1ff713.
