### ISSUE TITLE
"make test" fails on recent Perls

### ISSUE THREAD

**Issue by jdigory** [interchange/interchange#93]
This is the result of attempting to run `make test` for Interchange 5.10.0 with a plenv-managed Perl 5.22.0:

```
PERL_DL_NONLAZY=1 "/home/josh/.plenv/versions/5.22.0/bin/perl5.22.0" "-Iblib/lib" "-Iblib/arch" test.pl
server/unixmode.......ok 1
server/startup........ok 2
link/unixmode.........not ok 3

# When the above test fails, it may be due to your ISP or some other
# mechanism blocking port 8786.

server/inetmode.......ok 4
link/inetmode.........not ok 5
server/control........ok 6
6 tests run -- 2/6 failed.
make: *** [test_dynamic] Error 1
```

It fails the link/unixmode and link/inetmode tests. These are apparently not critical, but if that is truly the case, then they either shouldn't be in the test suite, or shouldn't be required to return ok.

**Comment by sbatschelet** [comment]
@jdigory perhaps we could cover them with something like ```unless ( $ENV{RELEASE_TESTING} )``` so that they could be run if RELEASE_TESTING is flagged during make but not required for install.

**Comment by jonjensen** [comment]
We need to find out what is wrong with the test and fix it. It works fine using Perl versions up to 5.16, but on 5.18 and newer it fails for me. I haven't yet figured out why.

**Comment by mckyj57** [comment]
Caused by the new Vend::Safe and its attempt to integrate UTF-8 routines into the Safe compartment. I used an environment variable to avoid the initialization when testing -- obviously this does not remove any underlying problem.

**Comment by jdigory** [comment]
Thanks, Mike. I've tested this change with the latest repo, and all tests pass for me with perl 5.22.0. IMO, we can close this bug, unless you all think we should research further. 

But I think having passing tests (regardless if there is still an underlying problem) will encourage new users to continue experimenting with Interchange; whereas failing tests will almost certainly discourage them. If there's a underlying problem, I haven't experienced it myself, but that doesn't mean we shouldn't try to fix it, only that I'm not sure just who would experience it...

**Comment by jdigory** [comment]
closing thanks to 672b8a11
