### ISSUE TITLE
Disallow comma character in emails

### ISSUE THREAD

**Issue by racke** [interchange/interchange#97]
Justification from https://www.jochentopf.com/email/chars.html

The comma is used in address header fields to separate email addresses from each other. Example: tarzan@jungle.org, jane@jungle.org. RFC2822 allowes their use if they are inside double quotes, but this would be very confusing. They are used in source routing, too. Don't use them in the local part.

Also Email::Valid flags addresses like foo,bar@test.de as shown in the following test:

https://github.com/racke/Data-Transpose/blob/master/t/transpose-email.t

Please let me know what you are thinking.

**Comment by jonjensen** [comment]
@racke Sounds reasonable to me.

The specific details seem important, in the absence of a patch. For example, user form profile checks of type "email" should prohibit commas, I would think, but the email tag should allow it, because developers may be wanting to send an email to multiple recipients.

**Comment by racke** [comment]
Yes, this is about the profile checks. I had this case a few time that users put a comma in their email address. I'll prepare a patch.

**Comment by racke** [comment]
Closed through 4ff70c2.
